services:
  - type: web
    name: gustabor-backend
    runtime: python
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You will set this manually in the Render dashboard
